"""trip updated

Revision ID: 1968305f95bc
Revises: 2da9c39e941b
Create Date: 2026-06-03 14:52:24.243138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1968305f95bc'
down_revision: Union[str, Sequence[str], None] = 'd811947a8470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Trip_logs')
    op.alter_column('trips', 'start_odometer',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trips', 'end_odometer',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trips', 'fuel_level_before',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trips', 'fuel_level_after',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'fuel_level_after',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trips', 'fuel_level_before',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trips', 'end_odometer',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trips', 'start_odometer',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('Trip_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('CHECKED_OUT', 'CHECKED_IN', 'CANCELLED', 'OVERDUE', name='tripaction'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['vechile_reservations.id'], name=op.f('Trip_logs_reservation_id_fkey')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('Trip_logs_trip_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Trip_logs_pkey'))
    )
    # ### end Alembic commands ###
