"""vehicle status  added

Revision ID: 56e77480a20d
Revises: d811947a8470
Create Date: 2026-06-02 16:28:19.863799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e77480a20d'
down_revision: Union[str, Sequence[str], None] = 'd811947a8470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'IN_USE', 'MAINTENANCE', 'OVERDUE', 'OUT_OF_SERVICE', name='vehicle_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'status')
    # ### end Alembic commands ###
