"""trip table start end time  updated

Revision ID: 7a76f9d65876
Revises: 1968305f95bc
Create Date: 2026-06-03 16:48:14.848573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a76f9d65876'
down_revision: Union[str, Sequence[str], None] = '1968305f95bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Trip_logs')
    op.add_column('trips', sa.Column('trip_start', sa.DateTime(), nullable=False))
    op.add_column('trips', sa.Column('trip_end', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'trip_end')
    op.drop_column('trips', 'trip_start')
    op.create_table('Trip_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('CHECKED_OUT', 'CHECKED_IN', 'CANCELLED', 'OVERDUE', name='tripaction'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['vechile_reservations.id'], name=op.f('Trip_logs_reservation_id_fkey')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('Trip_logs_trip_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Trip_logs_pkey'))
    )
    # ### end Alembic commands ###
