"""MAINTENACE TABLE UPDATED

Revision ID: 84b2dd4f5921
Revises: ce9fa4d1e255
Create Date: 2026-06-04 13:23:08.808836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84b2dd4f5921'
down_revision: Union[str, Sequence[str], None] = 'ce9fa4d1e255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenace_schedules', 'maintenance_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vehicles', 'maintenance_intervel',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vehicles', 'maintenance_atkms',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'maintenance_atkms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vehicles', 'maintenance_intervel',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('maintenace_schedules', 'maintenance_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
