"""columns add to vehicle table

Revision ID: 8afc63206a08
Revises: 3dfff00c744d
Create Date: 2026-06-04 00:49:54.261071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8afc63206a08'
down_revision: Union[str, Sequence[str], None] = '3dfff00c744d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('current_odometer', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('maintenance_intervel', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('maintenance_atkms', sa.Integer(), nullable=True))
    op.alter_column('vehicles', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'RESERVED', 'IN_USE', 'MAINTENANCE', 'OVERDUE', 'OUT_OF_SERVICE', name='vehicle_status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'RESERVED', 'IN_USE', 'MAINTENANCE', 'OVERDUE', 'OUT_OF_SERVICE', name='vehicle_status'),
               nullable=True)
    op.drop_column('vehicles', 'maintenance_atkms')
    op.drop_column('vehicles', 'maintenance_intervel')
    op.drop_column('vehicles', 'current_odometer')
    # ### end Alembic commands ###
