"""emp drving licensse column UPDATED

Revision ID: c4dcfd8afc7d
Revises: 84b2dd4f5921
Create Date: 2026-06-04 14:38:51.224580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4dcfd8afc7d'
down_revision: Union[str, Sequence[str], None] = '84b2dd4f5921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
