"""trip table  actual end time  updated

Revision ID: cb9ff5e99ee7
Revises: 4e4fc220100d
Create Date: 2026-06-03 17:50:16.169717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb9ff5e99ee7'
down_revision: Union[str, Sequence[str], None] = '4e4fc220100d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'check_in_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('trips', 'actual_end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'actual_end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('trips', 'check_in_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
