"""vehicle number added

Revision ID: d811947a8470
Revises: 01e3315650a7
Create Date: 2026-06-02 13:13:53.774982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd811947a8470'
down_revision: Union[str, Sequence[str], None] = '01e3315650a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'addharcard',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('vehicles', sa.Column('number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'vehicles', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_column('vehicles', 'number')
    op.alter_column('employees', 'addharcard',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
