"""trip table start , ecpected , actual end time  updated

Revision ID: de3eea06e019
Revises: 5cf62ff96760
Create Date: 2026-06-03 17:25:56.398404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de3eea06e019'
down_revision: Union[str, Sequence[str], None] = '5cf62ff96760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('expected_end_time', sa.DateTime(), nullable=False))
    op.add_column('trips', sa.Column('actual_end_time', sa.DateTime(), nullable=False))
    op.drop_column('trips', 'trip_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('trip_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('trips', 'actual_end_time')
    op.drop_column('trips', 'expected_end_time')
    # ### end Alembic commands ###
